version: "3"
services:
   flask1:
    build:
       context: .
       dockerfile: Dockerfile
    volumes:
       - python-docker
    ports: 
      - 8083:5000
    networks:
      - nfp1
    image: yyyy
    container_name: pqr
networks:
  nfp1:
     driver: bridge
volumes:
   python-docker: