version: "3"
services: 
   flask2:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - 8085:5000
      volumes:
        - python-docker
      networks:
        - nfp2
      image: xxxx
      container_name: xyz
networks:
   nfp2:
     driver: bridge
volumes:
   python-docker: