version: "3"
services:
  flask1:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8081:5000"
    networks:
      - network1flask
    volumes:
      - "python-docker"
    image: flask_app_1
    container_name: flask_container_1
  flask2:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:5000"
    networks:
      - network2flask
    volumes:
      - "python-docker"
    image: flask_app_2
    container_name: flask_container_2

networks:
  network1flask:
      driver: bridge
  network2flask:
      driver: bridge

volumes: 
   python-docker:

